import { translations } from "./translations";
import { godShlokas } from "./god-data";

export const DUMMY_PROFILES = [
  // ENGLISH PROFILES
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-1",
    godNames: [godShlokas.en[0]],
    photo: "/images/dummy/indian_man_1.webp",
    formData: {
      fullName: "Aditya Sharma",
      dob: "22/08/1994",
      birthTime: "08:15 AM",
      birthPlace: "Mumbai, Maharashtra",
      height: "5' 11\"",
      religion: "Hindu",
      caste: "Brahmin",
      gotra: "Kashyap",
      education: "B.Tech in IT",
      job: "Software Developer at TCS",
      salary: "18 LPA",
      fatherName: "Rajesh Sharma",
      fatherJob: "Business",
      motherName: "Suman Sharma",
      motherJob: "Housewife",
      brothers: "1 Younger",
      sisters: "None",
      mobile: "+91 XXXXX XXXXX",
      address: "Andheri West, Mumbai - 400053"
    }
  },
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-2",
    godNames: [godShlokas.en[1]],
    photo: "/images/dummy/indian_woman_1.webp",
    formData: {
      fullName: "Neha Patil",
      dob: "14/11/1996",
      birthTime: "06:30 PM",
      birthPlace: "Pune, Maharashtra",
      height: "5' 5\"",
      religion: "Hindu",
      caste: "Maratha",
      gotra: "Garg",
      education: "MBA Finance",
      job: "Financial Analyst",
      salary: "12 LPA",
      fatherName: "Vijay Patil",
      fatherJob: "Bank Manager",
      motherName: "Kavita Patil",
      motherJob: "Teacher",
      brothers: "None",
      sisters: "1 Elder (Married)",
      mobile: "+91 XXXXX XXXXX",
      address: "Kothrud, Pune - 411038"
    }
  },
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-3",
    godNames: [godShlokas.en[2]],
    photo: "/images/dummy/indian_man_2.webp",
    formData: {
      fullName: "Rohan Deshmukh",
      dob: "05/03/1993",
      birthTime: "11:45 AM",
      birthPlace: "Nagpur, Maharashtra",
      height: "5' 9\"",
      religion: "Hindu",
      caste: "Deshastha Brahmin",
      gotra: "Bharadwaj",
      education: "M.Arch",
      job: "Senior Architect",
      salary: "20 LPA",
      fatherName: "Prakash Deshmukh",
      fatherJob: "Retired Engineer",
      motherName: "Anjali Deshmukh",
      motherJob: "Homemaker",
      brothers: "1 Elder",
      sisters: "1 Younger",
      mobile: "+91 XXXXX XXXXX",
      address: "Dharampeth, Nagpur - 440010"
    }
  },
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-4",
    godNames: [godShlokas.en[0]],
    photo: "/images/dummy/indian_woman_2.webp",
    formData: {
      fullName: "Pooja Joshi",
      dob: "19/09/1997",
      birthTime: "04:20 AM",
      birthPlace: "Nashik, Maharashtra",
      height: "5' 4\"",
      religion: "Hindu",
      caste: "Kokanastha Brahmin",
      gotra: "Shandilya",
      education: "BDS",
      job: "Dentist",
      salary: "9 LPA",
      fatherName: "Sanjay Joshi",
      fatherJob: "Doctor",
      motherName: "Meena Joshi",
      motherJob: "Doctor",
      brothers: "1 Younger",
      sisters: "None",
      mobile: "+91 XXXXX XXXXX",
      address: "College Road, Nashik - 422005"
    }
  },

  // MARATHI PROFILES
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-1",
    godNames: [godShlokas.mr[0]],
    photo: "/images/dummy/indian_man_3.webp",
    formData: {
      fullName: "अमित जाधव",
      dob: "१२/०४/१९९५",
      birthTime: "सकाळी ०९:१०",
      birthPlace: "सातारा, महाराष्ट्र",
      height: "५ फूट ८ इंच",
      religion: "हिंदू",
      caste: "मराठा",
      gotra: "-",
      education: "बी.एस्सी. ॲग्री",
      job: "कृषी अधिकारी",
      salary: "८ लाख/वर्ष",
      fatherName: "रवींद्र जाधव",
      fatherJob: "शेती",
      motherName: "सुवर्णा जाधव",
      motherJob: "गृहिणी",
      brothers: "१ लहान",
      sisters: "१ मोठी (विवाहित)",
      mobile: "+91 XXXXX XXXXX",
      address: "मु. पो. सातारा, ता. सातारा, जि. सातारा"
    }
  },
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-2",
    godNames: [godShlokas.mr[1]],
    photo: "/images/dummy/indian_woman_3.webp",
    formData: {
      fullName: "स्नेहा कदम",
      dob: "२५/१०/१९९६",
      birthTime: "दुपारी ०२:४५",
      birthPlace: "कोल्हापूर, महाराष्ट्र",
      height: "५ फूट ३ इंच",
      religion: "हिंदू",
      caste: "९६ कुळी मराठा",
      gotra: "-",
      education: "एम. कॉम.",
      job: "बँक अधिकारी",
      salary: "६ लाख/वर्ष",
      fatherName: "शिवाजी कदम",
      fatherJob: "व्यापार",
      motherName: "लता कदम",
      motherJob: "गृहिणी",
      brothers: "नाही",
      sisters: "१ लहान",
      mobile: "+91 XXXXX XXXXX",
      address: "राजारामपुरी, कोल्हापूर - ४१६००८"
    }
  },
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-3",
    godNames: [godShlokas.mr[2]],
    photo: "/images/dummy/indian_man_1.webp",
    formData: {
      fullName: "विशाल काळे",
      dob: "०८/०७/१९९३",
      birthTime: "रात्री ०८:३०",
      birthPlace: "सोलापूर, महाराष्ट्र",
      height: "५ फूट १० इंच",
      religion: "हिंदू",
      caste: "धनगर",
      gotra: "कश्यप",
      education: "बी.ई. सिव्हिल",
      job: "स्थापत्य अभियंता",
      salary: "१० लाख/वर्ष",
      fatherName: "मारुती काळे",
      fatherJob: "निवृत्त शिक्षक",
      motherName: "रुक्मिणी काळे",
      motherJob: "गृहिणी",
      brothers: "१ मोठा (विवाहित)",
      sisters: "नाही",
      mobile: "+91 XXXXX XXXXX",
      address: "जुळे सोलापूर, सोलापूर - ४१३००४"
    }
  },

  // HINDI PROFILES
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-1",
    godNames: [godShlokas.hi[0]],
    photo: "/images/dummy/indian_man_2.webp",
    formData: {
      fullName: "राहुल वर्मा",
      dob: "18/06/1994",
      birthTime: "07:20 AM",
      birthPlace: "इंदौर, मध्य प्रदेश",
      height: "5 फ़ुट 9 इंच",
      religion: "हिंदू",
      caste: "राजपूत",
      gotra: "कश्यप",
      education: "एम.बी.ए.",
      job: "मार्केटिंग मैनेजर",
      salary: "15 लाख/वर्ष",
      fatherName: "सुरेश वर्मा",
      fatherJob: "व्यापारी",
      motherName: "सुनीता वर्मा",
      motherJob: "गृहिणी",
      brothers: "1 छोटा",
      sisters: "1 बड़ी (विवाहित)",
      mobile: "+91 XXXXX XXXXX",
      address: "विजयनगर, इंदौर - 452010"
    }
  },
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-4",
    godNames: [godShlokas.hi[1]],
    photo: "/images/dummy/indian_woman_1.webp",
    formData: {
      fullName: "अंजलि सिंह",
      dob: "22/01/1997",
      birthTime: "10:15 AM",
      birthPlace: "जयपुर, राजस्थान",
      height: "5 फ़ुट 4 इंच",
      religion: "हिंदू",
      caste: "राजपूत",
      gotra: "चौहान",
      education: "एम.एससी. कंप्यूटर साइंस",
      job: "सॉफ्टवेयर इंजीनियर",
      salary: "12 लाख/वर्ष",
      fatherName: "विक्रम सिंह",
      fatherJob: "सरकारी अधिकारी",
      motherName: "रीना सिंह",
      motherJob: "शिक्षिका",
      brothers: "नहीं",
      sisters: "1 छोटी",
      mobile: "+91 XXXXX XXXXX",
      address: "मालवीय नगर, जयपुर - 302017"
    }
  },
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-2",
    godNames: [godShlokas.hi[2]],
    photo: "/images/dummy/indian_man_3.webp",
    formData: {
      fullName: "सौरभ तिवारी",
      dob: "11/09/1993",
      birthTime: "05:40 PM",
      birthPlace: "लखनऊ, उत्तर प्रदेश",
      height: "5 फ़ुट 11 इंच",
      religion: "हिंदू",
      caste: "ब्राह्मण",
      gotra: "भारद्वाज",
      education: "बी.टेक. मैकेनिकल",
      job: "प्रोजेक्ट मैनेजर",
      salary: "18 लाख/वर्ष",
      fatherName: "रामेश्वर तिवारी",
      fatherJob: "व्यवसाय",
      motherName: "सुषमा तिवारी",
      motherJob: "गृहिणी",
      brothers: "1 बड़ा",
      sisters: "नहीं",
      mobile: "+91 XXXXX XXXXX",
      address: "गोमती नगर, लखनऊ - 226010"
    }
  },

  // ADDITIONAL ENGLISH PROFILES
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-3",
    godNames: [godShlokas.en[0]],
    photo: "/images/dummy/indian_woman_2.webp",
    formData: {
      fullName: "Priya Desai",
      dob: "03/12/1995",
      birthTime: "09:45 AM",
      birthPlace: "Ahmedabad, Gujarat",
      height: "5' 3\"",
      religion: "Hindu",
      caste: "Patel",
      gotra: "-",
      education: "CA",
      job: "Chartered Accountant",
      salary: "14 LPA",
      fatherName: "Kamlesh Desai",
      fatherJob: "Business",
      motherName: "Bhavna Desai",
      motherJob: "Housewife",
      brothers: "1 Elder",
      sisters: "None",
      mobile: "+91 XXXXX XXXXX",
      address: "Vastrapur, Ahmedabad - 380015"
    }
  },
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-1",
    godNames: [godShlokas.en[1]],
    photo: "/images/dummy/indian_man_1.webp",
    formData: {
      fullName: "Karan Mehta",
      dob: "27/07/1992",
      birthTime: "02:10 PM",
      birthPlace: "Surat, Gujarat",
      height: "5' 10\"",
      religion: "Hindu",
      caste: "Bania",
      gotra: "Kashyap",
      education: "B.Tech + MBA",
      job: "Product Manager",
      salary: "25 LPA",
      fatherName: "Rajeev Mehta",
      fatherJob: "Diamond Merchant",
      motherName: "Smita Mehta",
      motherJob: "Homemaker",
      brothers: "None",
      sisters: "1 Younger",
      mobile: "+91 XXXXX XXXXX",
      address: "Adajan, Surat - 395009"
    }
  },
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-4",
    godNames: [godShlokas.en[2]],
    photo: "/images/dummy/indian_woman_3.webp",
    formData: {
      fullName: "Ananya Iyer",
      dob: "16/05/1996",
      birthTime: "11:30 PM",
      birthPlace: "Chennai, Tamil Nadu",
      height: "5' 6\"",
      religion: "Hindu",
      caste: "Iyer Brahmin",
      gotra: "Srivatsa",
      education: "M.Sc Data Science",
      job: "Data Scientist",
      salary: "22 LPA",
      fatherName: "Venkatesh Iyer",
      fatherJob: "Bank Director",
      motherName: "Lakshmi Iyer",
      motherJob: "Professor",
      brothers: "1 Younger",
      sisters: "None",
      mobile: "+91 XXXXX XXXXX",
      address: "Mylapore, Chennai - 600004"
    }
  },

  // ADDITIONAL MARATHI PROFILES
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-1",
    godNames: [godShlokas.mr[0]],
    photo: "/images/dummy/indian_man_2.webp",
    formData: {
      fullName: "सुशांत पवार",
      dob: "२९/११/१९९१",
      birthTime: "सकाळी ०६:१५",
      birthPlace: "पुणे, महाराष्ट्र",
      height: "५ फूट ९ इंच",
      religion: "हिंदू",
      caste: "मराठा",
      gotra: "-",
      education: "बी. फार्मसी",
      job: "मेडिकल डिस्ट्रिब्युटर",
      salary: "१२ लाख/वर्ष",
      fatherName: "गोविंद पवार",
      fatherJob: "व्यवसाय",
      motherName: "शालन पवार",
      motherJob: "गृहिणी",
      brothers: "२ लहान",
      sisters: "नाही",
      mobile: "+९१ XXXXX XXXXX",
      address: "वारजे माळवाडी, पुणे - ४११०५८"
    }
  },
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-2",
    godNames: [godShlokas.mr[1]],
    photo: "/images/dummy/indian_woman_1.webp",
    formData: {
      fullName: "रुपाली भोसले",
      dob: "१४/०२/१९९८",
      birthTime: "दुपारी १२:३०",
      birthPlace: "छत्रपती संभाजीनगर",
      height: "५ फूट ४ इंच",
      religion: "हिंदू",
      caste: "९६ कुळी मराठा",
      gotra: "-",
      education: "बी. ए. बी. एड.",
      job: "शिक्षिका",
      salary: "५ लाख/वर्ष",
      fatherName: "प्रताप भोसले",
      fatherJob: "पोलीस उपनिरीक्षक",
      motherName: "संगिता भोसले",
      motherJob: "गृहिणी",
      brothers: "नाही",
      sisters: "२ मोठ्या",
      mobile: "+९१ XXXXX XXXXX",
      address: "सिडको एन-७, छत्रपती संभाजीनगर - ४३१००३"
    }
  },
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-3",
    godNames: [godShlokas.mr[2]],
    photo: "/images/dummy/indian_man_3.webp",
    formData: {
      fullName: "प्रशांत कुलकर्णी",
      dob: "०७/०९/१९९४",
      birthTime: "सायंकाळी ०५:४५",
      birthPlace: "सांगली, महाराष्ट्र",
      height: "५ फूट ८ इंच",
      religion: "हिंदू",
      caste: "देशस्थ ब्राह्मण",
      gotra: "कौशिक",
      education: "एम. ई. कम्प्युटर",
      job: "सॉफ्टवेअर इंजिनिअर",
      salary: "१६ लाख/वर्ष",
      fatherName: "सुधीर कुलकर्णी",
      fatherJob: "बँक व्यवस्थापक",
      motherName: "माधुरी कुलकर्णी",
      motherJob: "गृहिणी",
      brothers: "१ मोठा",
      sisters: "१ लहान",
      mobile: "+९१ XXXXX XXXXX",
      address: "विश्रामबाग, सांगली - ४१६४१५"
    }
  },

  // ADDITIONAL HINDI PROFILES
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-1",
    godNames: [godShlokas.hi[0]],
    photo: "/images/dummy/indian_woman_2.webp",
    formData: {
      fullName: "श्वेता अग्रवाल",
      dob: "25/11/1996",
      birthTime: "03:20 PM",
      birthPlace: "दिल्ली",
      height: "5 फ़ुट 5 इंच",
      religion: "हिंदू",
      caste: "अग्रवाल",
      gotra: "बंसल",
      education: "बी.कॉम (ऑनर्स)",
      job: "एचआर मैनेजर",
      salary: "10 लाख/वर्ष",
      fatherName: "अशोक अग्रवाल",
      fatherJob: "व्यापारी",
      motherName: "किरण अग्रवाल",
      motherJob: "गृहिणी",
      brothers: "1 छोटा",
      sisters: "नहीं",
      mobile: "+91 XXXXX XXXXX",
      address: "रोहिणी सेक्टर 9, नई दिल्ली - 110085"
    }
  },
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-4",
    godNames: [godShlokas.hi[1]],
    photo: "/images/dummy/indian_man_1.webp",
    formData: {
      fullName: "विकास चौहान",
      dob: "10/01/1993",
      birthTime: "08:10 AM",
      birthPlace: "आगरा, उत्तर प्रदेश",
      height: "6 फ़ुट",
      religion: "हिंदू",
      caste: "राजपूत",
      gotra: "कश्यप",
      education: "एम.बी.बी.एस.",
      job: "डॉक्टर",
      salary: "20 लाख/वर्ष",
      fatherName: "प्रताप चौहान",
      fatherJob: "सरकारी डॉक्टर",
      motherName: "मीना चौहान",
      motherJob: "गृहिणी",
      brothers: "नहीं",
      sisters: "2 बड़ी (विवाहित)",
      mobile: "+91 XXXXX XXXXX",
      address: "कमला नगर, आगरा - 282005"
    }
  },
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-2",
    godNames: [godShlokas.hi[2]],
    photo: "/images/dummy/indian_woman_3.webp",
    formData: {
      fullName: "निशा गुप्ता",
      dob: "18/08/1997",
      birthTime: "11:55 PM",
      birthPlace: "पटना, बिहार",
      height: "5 फ़ुट 2 इंच",
      religion: "हिंदू",
      caste: "वैश्य",
      gotra: "कश्यप",
      education: "एम.ए. इकोनॉमिक्स",
      job: "बैंक पीओ",
      salary: "8 लाख/वर्ष",
      fatherName: "राकेश गुप्ता",
      fatherJob: "व्यवसाय",
      motherName: "सुमन गुप्ता",
      motherJob: "गृहिणी",
      brothers: "1 बड़ा",
      sisters: "1 छोटी",
      mobile: "+91 XXXXX XXXXX",
      address: "कंकड़बाग, पटना - 800020"
    }
  },
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-3",
    godNames: [godShlokas.hi[0]],
    photo: "/images/dummy/indian_man_2.webp",
    formData: {
      fullName: "अंकित मिश्रा",
      dob: "05/04/1994",
      birthTime: "07:30 AM",
      birthPlace: "वाराणसी, उत्तर प्रदेश",
      height: "5 फ़ुट 10 इंच",
      religion: "हिंदू",
      caste: "ब्राह्मण",
      gotra: "वत्स",
      education: "एल.एल.बी.",
      job: "अधिवक्ता (वकील)",
      salary: "12 लाख/वर्ष",
      fatherName: "पंडित दीनदयाल मिश्रा",
      fatherJob: "शिक्षक",
      motherName: "शांति मिश्रा",
      motherJob: "गृहिणी",
      brothers: "2 छोटे",
      sisters: "नहीं",
      mobile: "+91 XXXXX XXXXX",
      address: "लंका, वाराणसी - 221005"
    }
  },
  {
    language: "gu",
    biodataTitle: "બાયોડેટા",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-1",
    godNames: [godShlokas.gu ? godShlokas.gu[0] : "શ્રી ગણેશાય નમઃ"],
    photo: "/images/dummy/indian_man_2.webp",
    formData: {
      fullName: "કિરણભાઈ પટેલ",
      dob: "૧૫/૦૫/૧૯૯૫",
      birthTime: "સવારે ૦૯:૩૦",
      birthPlace: "અમદાવાદ, ગુજરાત",
      height: "૫ ફૂટ ૯ ઇંચ",
      religion: "હિન્દુ",
      caste: "કડવા પટેલ",
      gotra: "-",
      rashi: "સિંહ",
      nakshatra: "અશ્વિની",
      education: "એમ.બી.એ. (ફાયનાન્સ)",
      job: "સોફ્ટવેર એન્જિનિયર",
      salary: "૧૨ લાખ प्रति વર્ષ",
      fatherName: "સુરેશભાઈ પટેલ",
      fatherJob: "નિવૃત્ત સરકારી અધિકારી",
      motherName: "સુનિતાબેન પટેલ",
      motherJob: "ગૃહિણી",
      brothers: "૧ મોટો (પરિણીત)",
      sisters: "૧ નાની",
      mobile: "+૯૧ XXXXX XXXXX",
      address: "અમદાવાદ, ગુજરાત"
    }
  },
  {
    language: "gu",
    biodataTitle: "બાયોડેટા",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: true,
    godPhotoId: "god-2",
    godNames: [godShlokas.gu ? godShlokas.gu[1] : "શ્રી ગણેશાય નમઃ"],
    photo: "/images/dummy/indian_woman_1.webp",
    formData: {
      fullName: "પ્રીતિબેન શાહ",
      dob: "૨૨/૧૧/૧૯host",
      birthTime: "બપોરે ૧૨:૩૦",
      birthPlace: "વડોદરા, ગુજરાત",
      height: "૫ ફૂટ ૪ ઇંચ",
      religion: "હિન્દુ",
      caste: "જૈન વણિક",
      gotra: "-",
      rashi: "તુલા",
      nakshatra: "ચિત્રા",
      education: "એમ.એસસી. બાયોટેકનોલોજી",
      job: "રિસર્ચ સાયન્ટિસ્ટ",
      salary: "૮ લાખ प्रति વર્ષ",
      fatherName: "કમલેશભાઈ શાહ",
      fatherJob: "વ્યવસાયી",
      motherName: "ભાવનાબેન શાહ",
      motherJob: "ગૃહિણી",
      brothers: "નાહી",
      sisters: "૧ નાની",
      mobile: "+૯૧ XXXXX XXXXX",
      address: "વડોદરા, ગુજરાત"
    }
  },
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_man_1.webp",
    formData: {
      fullName: "Imran Khan",
      dob: "12/10/1993",
      birthTime: "04:30 PM",
      birthPlace: "Bhopal, Madhya Pradesh",
      height: "5' 11\"",
      religion: "Islam",
      caste: "Pathan",
      sect: "Sunni",
      maslak: "Hanafi",
      education: "M.Tech in Artificial Intelligence",
      job: "Lead AI Engineer at Microsoft",
      salary: "28 LPA",
      fatherName: "Sajid Khan",
      fatherJob: "Government Contractor",
      motherName: "Yasmin Khan",
      motherJob: "Homemaker",
      brothers: "1 Elder (Married, Software Architect)",
      sisters: "1 Younger (Studying B.Pharm)",
      mobile: "+91 XXXXX XXXXX",
      address: "Arera Colony, Bhopal - 462016"
    }
  },
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_woman_1.webp",
    formData: {
      fullName: "Farhana Shaikh",
      dob: "08/04/1996",
      birthTime: "10:15 AM",
      birthPlace: "Lucknow, Uttar Pradesh",
      height: "5' 4\"",
      religion: "Islam",
      caste: "Sheikh",
      sect: "Sunni",
      maslak: "Hanafi",
      education: "M.Sc in Biotechnology",
      job: "Research Scientist at Sun Pharma",
      salary: "14 LPA",
      fatherName: "Dr. Abdul Shaikh",
      fatherJob: "Consultant Cardiologist",
      motherName: "Farida Shaikh",
      motherJob: "Retired School Principal",
      brothers: "None",
      sisters: "2 Elder (Both Married)",
      mobile: "+91 XXXXX XXXXX",
      address: "Hazratganj, Lucknow - 226001"
    }
  },
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_man_2.webp",
    formData: {
      fullName: "Zayd Ahmed",
      dob: "17/07/1992",
      birthTime: "02:40 PM",
      birthPlace: "Hyderabad, Telangana",
      height: "6' 0\"",
      religion: "Islam",
      caste: "Syed",
      sect: "Sunni",
      maslak: "Hanafi",
      education: "MS in Computer Science from Stanford",
      job: "Senior Software Architect at Google",
      salary: "45 LPA",
      fatherName: "Syed Mansoor Ahmed",
      fatherJob: "Retired IAS Officer",
      motherName: "Rukhsar Ahmed",
      motherJob: "Author & Homemaker",
      brothers: "1 Younger (Software Engineer at Amazon)",
      sisters: "None",
      mobile: "+91 XXXXX XXXXX",
      address: "Jubilee Hills, Hyderabad - 500033"
    }
  },
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_woman_2.webp",
    formData: {
      fullName: "Yasmin Alvi",
      dob: "29/03/1995",
      birthTime: "08:30 AM",
      birthPlace: "New Delhi",
      height: "5' 5\"",
      religion: "Islam",
      caste: "Sheikh",
      sect: "Sunni",
      maslak: "Hanafi",
      education: "MDS in Orthodontics",
      job: "Senior Orthodontist at Fortis Healthcare",
      salary: "18 LPA",
      fatherName: "Farooq Alvi",
      fatherJob: "Senior Advocate (Supreme Court)",
      motherName: "Dilshad Alvi",
      motherJob: "Senior Gynecologist",
      brothers: "1 Elder (Software Engineer in Germany)",
      sisters: "None",
      mobile: "+91 XXXXX XXXXX",
      address: "Vasant Kunj, New Delhi - 110070"
    }
  },
  // HINDI MUSLIM PROFILES
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_man_1.webp",
    formData: {
      fullName: "इमरान खान",
      dob: "12/10/1993",
      birthTime: "शाम 04:30",
      birthPlace: "भोपाल, मध्य प्रदेश",
      height: "5 फ़ुट 11 इंच",
      religion: "इस्लाम",
      caste: "पठान",
      sect: "सुन्नी",
      maslak: "हनाफ़ी",
      education: "एम.टेक (आर्टिफिशियल इंटेलिजेंस)",
      job: "लीड एआई इंजीनियर (माइक्रोसॉफ्ट)",
      salary: "28 लाख/वर्ष",
      fatherName: "साजिद खान",
      fatherJob: "सरकारी ठेकेदार",
      motherName: "यास्मीन खान",
      motherJob: "गृहिणी",
      brothers: "1 बड़ा भाई (विवाहित)",
      sisters: "1 छोटी बहन",
      mobile: "+91 XXXXX XXXXX",
      address: "अरेरा कॉलोनी, भोपाल - 462016"
    }
  },
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_woman_1.webp",
    formData: {
      fullName: "फरहाना शेख",
      dob: "08/04/1996",
      birthTime: "सुबह 10:15",
      birthPlace: "लखनऊ, उत्तर प्रदेश",
      height: "5 फ़ुट 4 इंच",
      religion: "इस्लाम",
      caste: "शेख",
      sect: "सुन्नी",
      maslak: "हनाफ़ी",
      education: "एम.एससी (बायोटेक्नोलॉजी)",
      job: "रिसर्च साइंटिस्ट (सन फार्मा)",
      salary: "14 लाख/वर्ष",
      fatherName: "डॉ. अब्दुल शेख",
      fatherJob: "हृदय रोग विशेषज्ञ",
      motherName: "फरीदा शेख",
      motherJob: "सेवानिवृत्त प्रधानाध्यापिका",
      brothers: "कोई नहीं",
      sisters: "2 बड़ी बहनें (विवाहित)",
      mobile: "+91 XXXXX XXXXX",
      address: "हजरतगंज, Lucknow - 226001"
    }
  },
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_man_2.webp",
    formData: {
      fullName: "ज़ैद अहमद",
      dob: "17/07/1992",
      birthTime: "दोपहर 02:40",
      birthPlace: "हैदराबाद, तेलंगाना",
      height: "6 फ़ुट",
      religion: "इस्लाम",
      caste: "सैयद",
      sect: "सुन्नी",
      maslak: "हनाफ़ी",
      education: "स्टैनफोर्ड से एमएस (कंप्यूटर साइंस)",
      job: "सीनियर सॉफ्टवेयर आर्किटेक्ट (गूगल)",
      salary: "45 लाख/वर्ष",
      fatherName: "सैयद मंसूर अहमद",
      fatherJob: "सेवानिवृत्त आईएएस अधिकारी",
      motherName: "रुखसार अहमद",
      motherJob: "लेखिका और गृहिणी",
      brothers: "1 छोटा भाई",
      sisters: "कोई नहीं",
      mobile: "+91 XXXXX XXXXX",
      address: "जुबली हिल्स, हैदराबाद - 500033"
    }
  },
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_woman_2.webp",
    formData: {
      fullName: "यास्मीन अल्वी",
      dob: "29/03/1995",
      birthTime: "सुबह 08:30",
      birthPlace: "नई दिल्ली",
      height: "5 फ़ुट 5 इंच",
      religion: "इस्लाम",
      caste: "शेख",
      sect: "सुन्नी",
      maslak: "हनाफ़ी",
      education: "एमडीएस (ऑर्थोडॉन्टिक्स)",
      job: "सीनियर ऑर्थोडॉन्टिस्ट (फोर्टिस अस्पताल)",
      salary: "18 लाख/वर्ष",
      fatherName: "फारूक अल्वी",
      fatherJob: "वरिष्ठ अधिवक्ता (सुप्रीम कोर्ट)",
      motherName: "दिलशाद अल्वी",
      motherJob: "सीनियर स्त्री रोग विशेषज्ञ",
      brothers: "1 बड़ा भाई",
      sisters: "कोई नहीं",
      mobile: "+91 XXXXX XXXXX",
      address: "वसंत कुंज, नई दिल्ली - 110070"
    }
  },
  // MARATHI MUSLIM PROFILES
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_man_1.webp",
    formData: {
      fullName: "इम्रान खान",
      dob: "१२/१०/१९९३",
      birthTime: "दुपारी ०४:३०",
      birthPlace: "भोपाळ, मध्य प्रदेश",
      height: "५ फूट ११ इंच",
      religion: "इस्लाम",
      caste: "पठाण",
      sect: "सुन्नी",
      maslak: "हनाफी",
      education: "एम.टेक (आर्टिफिशियल इंटेलिजन्स)",
      job: "लीड एआय इंजिनिअर (मायक्रोसॉफ्ट)",
      salary: "२८ लाख/वर्ष",
      fatherName: "साजिद खान",
      fatherJob: "सरकारी कंत्राटदार",
      motherName: "यास्मिन खान",
      motherJob: "गृहिणी",
      brothers: "१ मोठा भाऊ (विवाहित)",
      sisters: "१ लहान बहीण",
      mobile: "+९१ XXXXX XXXXX",
      address: "अरेरा कॉलनी, भोपाळ - ४६२०१६"
    }
  },
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_woman_1.webp",
    formData: {
      fullName: "फरहाना शेख",
      dob: "०८/०४/१९९६",
      birthTime: "सकाळी १०:१५",
      birthPlace: "लखनऊ, उत्तर प्रदेश",
      height: "५ फूट ४ इंच",
      religion: "इस्लाम",
      caste: "शेख",
      sect: "सुन्नी",
      maslak: "हनाफी",
      education: "एम.एससी (बायोटेक्नॉलॉजी)",
      job: "रिसर्च सायंटिस्ट (सन फार्मा)",
      salary: "१४ लाख/वर्ष",
      fatherName: "डॉ. अब्दुल शेख",
      fatherJob: "हृदयविकार तज्ज्ञ",
      motherName: "फरीदा शेख",
      motherJob: "सेवानिवृत्त मुख्याध्यापिका",
      brothers: "नाही",
      sisters: "२ मोठ्या बहिणी (विवाहित)",
      mobile: "+९१ XXXXX XXXXX",
      address: "हजरतगंज, लखनऊ - २२६००१"
    }
  },
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_man_2.webp",
    formData: {
      fullName: "झैद अहमद",
      dob: "१७/०७/१९९२",
      birthTime: "दुपारी ०२:४०",
      birthPlace: "हैदराबाद, तेलंगणा",
      height: "६ फूट",
      religion: "इस्लाम",
      caste: "सैयद",
      sect: "सुन्नी",
      maslak: "हनाफी",
      education: "स्टॅनफोर्ड मधून एमएस (संगणक शास्त्र)",
      job: "सीनियर सॉफ्टवेअर आर्किटेक्ट (गुगल)",
      salary: "४५ लाख/वर्ष",
      fatherName: "सैयद मन्सूर अहमद",
      fatherJob: "सेवानिवृत्त आयएएस अधिकारी",
      motherName: "रुखसार अहमद",
      motherJob: "लेखिका आणि गृहिणी",
      brothers: "१ लहान भाऊ",
      sisters: "नाही",
      mobile: "+९१ XXXXX XXXXX",
      address: "जुबली हिल्स, हैदराबाद - ५०००३३"
    }
  },
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/muslim_woman_2.webp",
    formData: {
      fullName: "यास्मिन अल्वी",
      dob: "२९/०३/१९९५",
      birthTime: "सकाळी ०८:३०",
      birthPlace: "नवी दिल्ली",
      height: "५ फूट ५ इंच",
      religion: "इस्लाम",
      caste: "शेख",
      sect: "सुन्नी",
      maslak: "हनाफी",
      education: "एमडीएस (ऑर्थोडॉन्टिक्स)",
      job: "सीनियर ऑर्थोडॉन्टिस्ट (फोर्टिस हॉस्पिटल)",
      salary: "१८ लाख/वर्ष",
      fatherName: "फारूक अल्वी",
      fatherJob: "वरिष्ठ वकील (सर्वोच्च न्यायालय)",
      motherName: "दिलशाद अल्वी",
      motherJob: "स्त्रीरोग तज्ज्ञ",
      brothers: "१ मोठा भाऊ",
      sisters: "नाही",
      mobile: "+९१ XXXXX XXXXX",
      address: "वसंत कुंज, नवी दिल्ली - ११०MD७०"
    }
  },
  // SIKH ENGLISH PROFILES
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/sikh_man.webp",
    formData: {
      fullName: "Manpreet Singh",
      dob: "18/09/1994",
      birthTime: "11:30 AM",
      birthPlace: "Amritsar, Punjab",
      height: "6' 0\"",
      religion: "Sikh",
      caste: "Jatt",
      sect: "Keshdhari",
      education: "MBA in Finance from IBS Hyderabad",
      job: "Investment Banker at HSBC",
      salary: "22 LPA",
      fatherName: "Sardar Gurdev Singh",
      fatherJob: "Retired Army Colonel",
      motherName: "Sardarni Harpreet Kaur",
      motherJob: "High School Teacher",
      brothers: "1 Elder (Married, Merchant Navy Officer)",
      sisters: "None",
      mobile: "+91 XXXXX XXXXX",
      address: "Ranjit Avenue, Amritsar - 143001"
    }
  },
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/sikh_woman.webp",
    formData: {
      fullName: "Jasleen Kaur",
      dob: "24/11/1996",
      birthTime: "08:15 AM",
      birthPlace: "Chandigarh",
      height: "5' 6\"",
      religion: "Sikh",
      caste: "Arora",
      sect: "Sehajdhari",
      education: "M.Tech in Computer Science",
      job: "Senior Software Engineer at Adobe",
      salary: "18 LPA",
      fatherName: "Sardar Balbir Singh",
      fatherJob: "Industrialist",
      motherName: "Sardarni Jaswinder Kaur",
      motherJob: "Homemaker",
      brothers: "None",
      sisters: "1 Younger (Studying Dental Surgery)",
      mobile: "+91 XXXXX XXXXX",
      address: "Sector 15, Chandigarh - 160015"
    }
  },
  // CHRISTIAN ENGLISH PROFILES
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/christian_man.webp",
    formData: {
      fullName: "David D'Souza",
      dob: "14/02/1993",
      birthTime: "03:45 PM",
      birthPlace: "Goa",
      height: "5' 10\"",
      religion: "Christian",
      caste: "St. Francis Xavier Church",
      sect: "Roman Catholic",
      education: "B.Arch from Sir JJ College of Architecture",
      job: "Senior Architect at Talati & Partners",
      salary: "16 LPA",
      fatherName: "Joseph D'Souza",
      fatherJob: "Retired Bank Manager",
      motherName: "Maria D'Souza",
      motherJob: "High School Vice-Principal",
      brothers: "1 Younger (Civil Engineer in Dubai)",
      sisters: "None",
      mobile: "+91 XXXXX XXXXX",
      address: "Miramar, Panaji, Goa - 403001"
    }
  },
  {
    language: "en",
    biodataTitle: "BIODATA",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/christian_woman.webp",
    formData: {
      fullName: "Michelle Pereira",
      dob: "21/07/1995",
      birthTime: "09:00 AM",
      birthPlace: "Mumbai, Maharashtra",
      height: "5' 4\"",
      religion: "Christian",
      caste: "St. Michael's Church, Mahim",
      sect: "Roman Catholic",
      education: "MBA in HR from NMIMS Mumbai",
      job: "HR Manager at TCS",
      salary: "12 LPA",
      fatherName: "Francis Pereira",
      fatherJob: "Government Gazette Officer",
      motherName: "Helen Pereira",
      motherJob: "Homemaker",
      brothers: "None",
      sisters: "1 Elder (Married, Microbiologist in US)",
      mobile: "+91 XXXXX XXXXX",
      address: "Mahim West, Mumbai - 400016"
    }
  },
  // SIKH HINDI PROFILES
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/sikh_man.webp",
    formData: {
      fullName: "मनप्रीत सिंह",
      dob: "18/09/1994",
      birthTime: "सुबह 11:30",
      birthPlace: "अमृतसर, पंजाब",
      height: "6 फ़ुट",
      religion: "सिख",
      caste: "जट्ट",
      sect: "केशधारी",
      education: "आईबीएस हैदराबाद से एमबीए (फाइनेंस)",
      job: "एचएसबीसी में इन्वेस्टमेंट बैंकर",
      salary: "22 लाख/वर्ष",
      fatherName: "सरदार गुरदेव सिंह",
      fatherJob: "सेवानिवृत्त सेना कर्नल",
      motherName: "सरदारनी हरप्रीत कौर",
      motherJob: "शिक्षिका",
      brothers: "1 बड़ा भाई (विवाहित)",
      sisters: "कोई नहीं",
      mobile: "+91 XXXXX XXXXX",
      address: "रंजीत एवेन्यू, अमृतसर - 143001"
    }
  },
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/sikh_woman.webp",
    formData: {
      fullName: "जसलीन कौर",
      dob: "24/11/1996",
      birthTime: "सुबह 08:15",
      birthPlace: "चंडीगढ़",
      height: "5 फ़ुट 6 इंच",
      religion: "सिख",
      caste: "अरोड़ा",
      sect: "सहजधारी",
      education: "एम.टेक (कंप्यूटर साइंस)",
      job: "एडोब में सीनियर सॉफ्टवेयर इंजीनियर",
      salary: "18 लाख/वर्ष",
      fatherName: "सरदार बलबीर सिंह",
      fatherJob: "उद्योगपति",
      motherName: "सरदारनी जसविंदर कौर",
      motherJob: "गृहिणी",
      brothers: "कोई नहीं",
      sisters: "1 छोटी बहन (बीडीएस छात्र)",
      mobile: "+91 XXXXX XXXXX",
      address: "सेक्टर 15, चंडीगढ़ - 160015"
    }
  },
  // CHRISTIAN HINDI PROFILES
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/christian_man.webp",
    formData: {
      fullName: "डेविड डिसूजा",
      dob: "14/02/1993",
      birthTime: "दोपहर 03:45",
      birthPlace: "गोवा",
      height: "5 फ़ुट 10 इंच",
      religion: "क्रिश्चियन",
      caste: "सेंट फ्रांसिस जेवियर चर्च",
      sect: "रोमन कैथोलिक",
      education: "सर जेजे कॉलेज ऑफ आर्किटेक्चर से बी.आर्क",
      job: "तालाती एंड पार्टनर्स में सीनियर आर्किटेक्ट",
      salary: "16 लाख/वर्ष",
      fatherName: "जोसेफ डिसूजा",
      fatherJob: "सेवानिवृत्त बैंक प्रबंधक",
      motherName: "मारिया डिसूजा",
      motherJob: "हाई स्कूल उप-प्रधानाचार्या",
      brothers: "1 छोटा भाई (दुबई में सिविल इंजीनियर)",
      sisters: "कोई नहीं",
      mobile: "+91 XXXXX XXXXX",
      address: "मिरामार, पणजी, गोवा - 403001"
    }
  },
  {
    language: "hi",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/christian_woman.webp",
    formData: {
      fullName: "मिशेल परेरा",
      dob: "21/07/1995",
      birthTime: "सुबह 09:00",
      birthPlace: "मुंबई, महाराष्ट्र",
      height: "5 फ़ुट 4 इंच",
      religion: "क्रिश्चियन",
      caste: "सेंट माइकल चर्च, माहिम",
      sect: "रोमन कैथोलिक",
      education: "एनएमआईएमएस मुंबई से एमबीए (एचआर)",
      job: "टीसीएस में एचआर मैनेजर",
      salary: "12 लाख/वर्ष",
      fatherName: "फ्रांसिस परेरा",
      fatherJob: "राजपत्रित सरकारी अधिकारी",
      motherName: "हेलेन परेरा",
      motherJob: "गृहिणी",
      brothers: "कोई नहीं",
      sisters: "1 बड़ी बहन (विवाहित)",
      mobile: "+91 XXXXX XXXXX",
      address: "माहिम वेस्ट, मुंबई - 400016"
    }
  },
  // SIKH MARATHI PROFILES
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/sikh_man.webp",
    formData: {
      fullName: "मनप्रीत सिंग",
      dob: "१८/०९/१९९४",
      birthTime: "सकाळी ११:३०",
      birthPlace: "अमृतसर, पंजाब",
      height: "६ फूट",
      religion: "सिख",
      caste: "जट्ट",
      sect: "केशधारी",
      education: "एमबीए (फायनान्स)",
      job: "इन्व्हेस्टमेंट बँकर (HSBC)",
      salary: "२२ लाख/वर्ष",
      fatherName: "सरदार गुरदेव सिंग",
      fatherJob: "सेवानिवृत्त लष्करी कर्नल",
      motherName: "सरदारनी हरप्रीत कौर",
      motherJob: "शिक्षिका",
      brothers: "१ मोठा भाऊ (विवाहित)",
      sisters: "नाही",
      mobile: "+९१ XXXXX XXXXX",
      address: "रणजीत एव्हेन्यू, अमृतसर - १४३००१"
    }
  },
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/sikh_woman.webp",
    formData: {
      fullName: "जसलीन कौर",
      dob: "२४/११/१९९६",
      birthTime: "सकाळी ०८:१५",
      birthPlace: "चंदिगढ",
      height: "५ फूट ६ इंच",
      religion: "सिख",
      caste: "अरोरा",
      sect: "सहजधारी",
      education: "एम.टेक (संगणक शास्त्र)",
      job: "सीनियर सॉफ्टवेअर इंजिनिअर (Adobe)",
      salary: "१८ लाख/वर्ष",
      fatherName: "सरदार बलवीर सिंग",
      fatherJob: "उद्योजक",
      motherName: "सरदारनी जसविंदर कौर",
      motherJob: "गृहिणी",
      brothers: "नाही",
      sisters: "१ लहान बहीण (बीडीएस विद्यार्थिनी)",
      mobile: "+९१ XXXXX XXXXX",
      address: "सेक्टर १५, चंदिगढ - १६००१५"
    }
  },
  // CHRISTIAN MARATHI PROFILES
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/christian_man.webp",
    formData: {
      fullName: "डेव्हिड डिसूझा",
      dob: "१४/०२/१९९३",
      birthTime: "दुपारी ०३:४५",
      birthPlace: "गोवा",
      height: "५ फूट १० इंच",
      religion: "ख्रिश्चन",
      caste: "सेंट फ्रान्सिस जेव्हियर चर्च",
      sect: "रोमन कॅथलिक",
      education: "बी.आर्क (सर जेजे कॉलेज ऑफ आर्किटेक्चर)",
      job: "सीनियर आर्किटेक्ट (तालाती अँड पार्टनर्स)",
      salary: "१६ लाख/वर्ष",
      fatherName: "जोसेफ डिसूझा",
      fatherJob: "सेवानिवृत्त बँक व्यवस्थापक",
      motherName: "मारिया डिसूझा",
      motherJob: "हायस्कूल उपप्राचार्या",
      brothers: "१ लहान भाऊ (दुबईमध्ये सिव्हिल इंजिनिअर)",
      sisters: "नाही",
      mobile: "+९१ XXXXX XXXXX",
      address: "मिरामार, पणजी, गोवा - ४०३००१"
    }
  },
  {
    language: "mr",
    biodataTitle: "बायोडेटा",
    showBiodataTitle: true,
    showGodPhoto: true,
    showGodName: false,
    godPhotoId: "",
    godNames: [],
    photo: "/images/dummy/christian_woman.webp",
    formData: {
      fullName: "मिशेल परेरा",
      dob: "२१/०७/१९९५",
      birthTime: "सकाळी ०९:००",
      birthPlace: "मुंबई, महाराष्ट्र",
      height: "५ फूट ४ इंच",
      religion: "ख्रिश्चन",
      caste: "सेंट मायकल चर्च, माहीम",
      sect: "रोमन कॅथलिक",
      education: "एमबीए एचआर (NMIMS मुंबई)",
      job: "एचआर मॅनेजर (TCS)",
      salary: "१२ लाख/वर्ष",
      fatherName: "फ्रान्सिस परेरा",
      fatherJob: "राजपत्रित सरकारी अधिकारी",
      motherName: "हेलन परेरा",
      motherJob: "गृहिणी",
      brothers: "नाही",
      sisters: "१ मोठी बहीण (विवाहित)",
      mobile: "+९१ XXXXX XXXXX",
      address: "माहीम वेस्ट, मुंबई - ४००MDE१६"
    }
  }
];

// Re-usable step fields definition to apply to all dummy profiles dynamically
const STEP_FIELDS = {
  1: [
    { id: 'fullName', labelId: 'fullName' },
    { id: 'dob', labelId: 'dob' },
    { id: 'birthTime', labelId: 'birthTime', customLabel: 'Birth Time' },
    { id: 'birthPlace', labelId: 'birthPlace' },
    { id: 'height', labelId: 'height' },
    { id: 'blood', labelId: 'blood' },
    { id: 'complexion', labelId: 'complexion' },
    { id: 'religion', labelId: 'religion' },
    { id: 'caste', labelId: 'caste' },
    { id: 'gotra', labelId: 'gotra' },
    { id: 'rashi', labelId: 'rashi' },
    { id: 'nakshatra', labelId: 'nakshatra' },
    { id: 'manglik', labelId: 'manglik' },
    { id: 'gan', labelId: 'gan' },
    { id: 'education', labelId: 'education' },
    { id: 'job', labelId: 'job' },
    { id: 'salary', labelId: 'salary' },
  ],
  2: [
    { id: 'fatherName', labelId: 'fatherName' },
    { id: 'fatherJob', labelId: 'fatherOccupation' },
    { id: 'motherName', labelId: 'motherName' },
    { id: 'motherJob', labelId: 'motherOccupation' },
    { id: 'brothers', labelId: 'brothers' },
    { id: 'sisters', labelId: 'sisters' },
    { id: 'mama', labelId: 'mama' },
    { id: 'nativePlace', labelId: 'nativePlace' },
  ],
  3: [
    { id: 'mobile', labelId: 'mobile' },
    { id: 'email', labelId: 'email' },
    { id: 'address', labelId: 'address' },
  ]
};

// Process the raw profiles into the expected format for getTemplateData
export const processedDummyProfiles = DUMMY_PROFILES.map(profile => {
  const lang = profile.language as 'en' | 'hi' | 'mr' | 'gu' | 'kn' | 'te' | 'ml' | 'bn';
  const t = translations[lang] || translations.en;

  const fd = profile.formData as any;
  const isIslam = ["islam", "इस्लाम"].includes(fd.religion?.toLowerCase() || "");
  const isSikh = ["sikh", "सिख"].includes(fd.religion?.toLowerCase() || "");
  const isChristian = ["christian", "क्रिश्चियन", "ख्रिश्चन"].includes(fd.religion?.toLowerCase() || "");
  const isNonAstrological = isIslam || isSikh || isChristian;

  // Inject extra dummy data for fields that aren't explicitly defined in DUMMY_PROFILES
  // to make the template look fully populated.
  const extendedFormData = {
    ...profile.formData,
    blood: fd.blood || "O+ Positive",
    complexion: fd.complexion || (lang === 'mr' ? 'गव्हाळ' : lang === 'hi' ? 'गेहुआ' : 'Fair'),
    rashi: isNonAstrological ? undefined : (fd.rashi || (lang === 'mr' ? 'सिंह' : lang === 'hi' ? 'सिंह' : 'Leo')),
    nakshatra: isNonAstrological ? undefined : (fd.nakshatra || (lang === 'mr' ? 'अश्विनी' : lang === 'hi' ? 'अश्विनी' : 'Ashwini')),
    manglik: isNonAstrological ? undefined : (fd.manglik || (lang === 'mr' ? 'नाही' : lang === 'hi' ? 'नहीं' : 'No')),
    gan: isNonAstrological ? undefined : (fd.gan || (lang === 'mr' ? 'मनुष्य' : lang === 'hi' ? 'मनुष्य' : 'Manushya')),
    gotra: isNonAstrological ? undefined : (fd.gotra || "-"),
    mama: fd.mama || (lang === 'mr' ? 'श्री. अनिल पाटील' : lang === 'hi' ? 'श्री अनिल वर्मा' : 'Mr. Anil Kumar'),
    nativePlace: fd.nativePlace || (lang === 'mr' ? 'पुणे, महाराष्ट्र' : lang === 'hi' ? 'जयपुर, राजस्थान' : 'Mumbai, MH'),
    email: fd.email || "contact@example.com",
    birthTime: fd.birthTime || (lang === 'mr' ? 'सकाळी ०९:३०' : lang === 'hi' ? 'सुबह 09:30' : '09:30 AM')
  };

  let currentStepFields = STEP_FIELDS;
  if (isIslam) {
    currentStepFields = {
      ...STEP_FIELDS,
      1: [
        { id: 'fullName', labelId: 'fullName' },
        { id: 'dob', labelId: 'dob' },
        { id: 'birthTime', labelId: 'birthTime', customLabel: 'Birth Time' },
        { id: 'birthPlace', labelId: 'birthPlace' },
        { id: 'height', labelId: 'height' },
        { id: 'blood', labelId: 'blood' },
        { id: 'complexion', labelId: 'complexion' },
        { id: 'religion', labelId: 'religion' },
        { id: 'sect', labelId: 'sect', customLabel: 'Sect' },
        { id: 'maslak', labelId: 'maslak', customLabel: 'Maslak' },
        { id: 'caste', labelId: 'caste', customLabel: 'Community/Caste' },
        { id: 'education', labelId: 'education' },
        { id: 'job', labelId: 'job' },
        { id: 'salary', labelId: 'salary' },
      ]
    };
  } else if (isSikh) {
    currentStepFields = {
      ...STEP_FIELDS,
      1: [
        { id: 'fullName', labelId: 'fullName' },
        { id: 'dob', labelId: 'dob' },
        { id: 'birthTime', labelId: 'birthTime', customLabel: lang === 'mr' ? 'जन्माची वेळ' : lang === 'hi' ? 'जन्म समय' : 'Birth Time' },
        { id: 'birthPlace', labelId: 'birthPlace' },
        { id: 'height', labelId: 'height' },
        { id: 'blood', labelId: 'blood' },
        { id: 'complexion', labelId: 'complexion' },
        { id: 'religion', labelId: 'religion' },
        { id: 'sect', labelId: 'sect', customLabel: lang === 'mr' ? 'पंथ' : lang === 'hi' ? 'पंथ' : 'Sect/Affiliation' },
        { id: 'caste', labelId: 'caste', customLabel: lang === 'mr' ? 'जात/कुळ' : lang === 'hi' ? 'जाति/गोत्र' : 'Caste/Clan' },
        { id: 'education', labelId: 'education' },
        { id: 'job', labelId: 'job' },
        { id: 'salary', labelId: 'salary' },
      ]
    };
  } else if (isChristian) {
    currentStepFields = {
      ...STEP_FIELDS,
      1: [
        { id: 'fullName', labelId: 'fullName' },
        { id: 'dob', labelId: 'dob' },
        { id: 'height', labelId: 'height' },
        { id: 'blood', labelId: 'blood' },
        { id: 'complexion', labelId: 'complexion' },
        { id: 'religion', labelId: 'religion' },
        { id: 'sect', labelId: 'sect', customLabel: lang === 'mr' ? 'पंथ/पद्धत' : lang === 'hi' ? 'पंथ/वर्ग' : 'Denomination' },
        { id: 'caste', labelId: 'caste', customLabel: lang === 'mr' ? 'चर्च/पॅरिश' : lang === 'hi' ? 'चर्च/पैरिश' : 'Parish/Church' },
        { id: 'education', labelId: 'education' },
        { id: 'job', labelId: 'job' },
        { id: 'salary', labelId: 'salary' },
      ]
    };
  }

  return {
    ...profile,
    profilePhotoUrl: profile.photo,
    formData: extendedFormData,
    stepFields: currentStepFields,
    stepHeadings: {
      1: t.personalDetails,
      2: t.familyDetails,
      3: t.contactDetails
    }
  };
});



export function getDummyBiodata(community?: string) {
  if (!community) return processedDummyProfiles[0];

  const c = community.toLowerCase();

  // Filter profiles whose religion matches the requested community
  const matching = processedDummyProfiles.filter(p => {
    const rel = (p.formData?.religion || "").toLowerCase();
    if (c.includes("sikh") && rel.includes("sikh")) return true;
    if (c.includes("christian") && (rel.includes("christian") || rel.includes("क्रिश्चियन") || rel.includes("ख्रिश्चन"))) return true;
    if ((c.includes("muslim") || c.includes("islam")) && (rel.includes("islam") || rel.includes("इस्लाम"))) return true;
    if (c.includes("hindu") && rel.includes("hindu")) return true;
    return false;
  });

  if (matching.length > 0) {
    // Pick a stable (deterministic) profile from the matches to avoid hydration issues
    return matching[0];
  }

  // Default: first Hindu English profile
  return processedDummyProfiles[0];
}
